sudo: required
services:
  - docker

before_install:
  - docker build -t silvanhab/react-test:latest -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true silvanhab/react-test npm run test -- --coverage

after_success:
  - docker build -t silvanhab/multi-client:latest ./client
  - docker build -t silvanhab/multi-nginx:latest ./nginx
  - docker build -t silvanhab/multi-server:latest ./server
  - docker build -t silvanhab/multi-worker:latest ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push to dockerhub
  - docker push silvanhab/multi-client
  - docker push silvanhab/multi-nginx
  - docker push silvanhab/multi-server
  - docker push silvanhab/multi-worker

deploy: 
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env-2
  bucket_name: elasticbeanstalk-us-east-2-013130444661
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY